# Generated by Django 2.0.9 on 2018-10-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert_blog',
            name='blogger_name',
            field=models.CharField(default='random_blogger', max_length=30),
        ),
        migrations.AlterField(
            model_name='insert_blog',
            name='blog_post_name',
            field=models.CharField(default='random_blog', max_length=50),
        ),
    ]
