# Generated by Django 2.0.9 on 2018-10-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20181020_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='random_blogger', max_length=30)),
                ('user_id', models.IntegerField()),
                ('blog_name', models.CharField(default='random_blog', max_length=30)),
                ('blog_url', models.URLField()),
            ],
        ),
    ]
