# Generated by Django 2.0.9 on 2018-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert_blog',
            name='Blog_link',
            field=models.URLField(default='www.sanjumsanthosh.pythonanywhere.com'),
        ),
    ]
