# Generated by Django 2.0.9 on 2018-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_insert_blog_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='blog_url',
            field=models.CharField(max_length=20),
        ),
    ]
