# Generated by Django 2.0.9 on 2018-10-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20181020_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert_blog',
            name='Blog_link',
            field=models.TextField(default='www.sanjumsanthosh.pythonanywhere.com'),
        ),
    ]
