# Generated by Django 2.0.9 on 2018-11-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20181020_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insert_blog',
            old_name='user_id',
            new_name='view_counter',
        ),
    ]
