# Generated by Django 2.0.9 on 2018-11-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20181103_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert_blog',
            name='image_name',
        ),
    ]
