# Generated by Django 2.0.9 on 2018-11-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_insert_blog_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert_blog',
            name='image_upload',
            field=models.ImageField(default='post-1.jpg', upload_to='media'),
        ),
    ]
