# Generated by Django 2.0.9 on 2018-11-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_insert_blog_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_data_collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
            ],
        ),
    ]
